{{- if not $.Values.mcgstandalone.enabled }}
---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
  - storagecluster.ocs.openshift.io
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  arbiter: {}
  {{- if eq $.Values.osds.scname "localblock" }}
  flexibleScaling: {{ default "true" $.Values.odf.flexibleScaling }}
  {{- else}}
  flexibleScaling: {{ default "false" $.Values.odf.flexibleScaling }}
  {{- end }}
  encryption:
  {{- if $.Values.osds.encryption.enabled }}
    enable: true
  {{- else}}
    enable: false
  {{- end }}
    kms: {}
    clusterWide: true
  externalStorage: {}
  managedResources:
    cephBlockPools: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
  {{- if not $.Values.mcg.enabled }}
  multiCloudGateway:
    reconcileStrategy: ignore
  {{- end }}
  {{- if eq $.Values.osds.scname "localblock" }}
  monDataDirHostPath: /var/lib/rook
  {{- end }}
  nodeTopologies: {}
  storageDeviceSets:
  - config: {}
    {{- if eq $.Values.osds.scname "localblock" }}
    count: {{ default "1" $.Values.osds.devicesetcount }}
    {{- else}}
    count: {{ default "1" $.Values.osds.devicesetcount }}
    {{- end }}
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            {{- if eq $.Values.osds.scname "localblock" }}
            storage: 1
            {{- else}}
            storage: {{ $.Values.osds.disksize }}
            {{- end }}
        storageClassName: {{ $.Values.osds.scname }}
        volumeMode: Block
      status: {}
    name: ocs-deviceset-{{ $.Values.osds.scname }}
    placement: {}
    {{- if eq $.Values.osds.scname "localblock" }}
    portable: false
    {{- else}}
    portable: true
    {{- end }}
    preparePlacement: {}
    replica: {{ default "3 " $.Values.osds.replicas }}
    resources: {}
{{- end }}
